import Foundation

/// The Start-Over wizard's answers. Sent to the `coach` Edge Function (camelCase
/// keys, matching the function's `Brief` type) and stored on `programs.brief`.
struct Brief: Codable, Equatable {
    var goal: String?          // "Build muscle", "Lose fat", "Get stronger", "Sport performance", "General health"
    var route: String?         // "Padel", "Gym — Hypertrophy", "Boxing", …
    var sport: String?         // free-text sport when the route is "Other"
    var daysPerWeek: Int?      // 2–6
    var sessionMinutes: Int?   // ~45, 60, 75
    var equipment: String?     // "Full gym", "Home", "Minimal"
    var level: String?         // "New", "Some", "Experienced"
}

/// A program as generated by Claude (the `result` of coach `mode:"program"`).
/// Re-sent verbatim on commit, so the field names mirror the function's JSON.
struct GenProgram: Codable {
    var name: String
    var summary: String?
    var days: [GenDay]
}

struct GenDay: Codable, Identifiable {
    var id = UUID()
    var name: String
    var sessionType: String?
    var focus: String?
    var exercises: [GenExercise]

    enum CodingKeys: String, CodingKey {
        case name, focus, exercises
        case sessionType = "session_type"
    }
}

struct GenExercise: Codable, Identifiable {
    var id = UUID()
    var name: String
    var muscle: String?
    var sets: Int?
    var reps: String?
    var note: String?

    enum CodingKeys: String, CodingKey { case name, muscle, sets, reps, note }
}
