-- AI-generated programs + photo "chapters"
-- ---------------------------------------------------------------------------
-- The Start-Over wizard lets a member pick a sport/goal and have Claude build a
-- strength & conditioning program for it. Such programs are user-owned (like a
-- cloned template) but flagged so the UI can show "AI-built" and recall the
-- brief that produced them. Progress photos gain a denormalized program label so
-- the gallery can group shots into chapters by the program active when taken.

-- programs.source: how this program came to exist.
--   'template' = cloned from a global template (the default, existing behaviour)
--   'ai'       = generated by the coach function from a wizard brief
--   'custom'   = hand-built
alter table programs
  add column if not exists source text not null default 'template';

-- programs.brief: the wizard answers that produced an AI program
--   { goal, route, sport, days_per_week, session_minutes, equipment, level }
alter table programs
  add column if not exists brief jsonb;

-- progress_photos.program_label: the active program's name at upload time, so
-- the gallery can subtitle/group photos by the program that was running. Null
-- for photos taken before this column existed — they keep their cycle/week tag.
alter table progress_photos
  add column if not exists program_label text;
